services:
    web:
        restart: always
        build: .
        container_name: web-container
        command: uvicorn mcdonalds_scraper.api.main:app --reload --host 0.0.0.0
        ports:
          - "8000:8000"
        volumes:
            - .:/app
